image: barichello/godot-ci:4.2.2

# # NOTE: the `cd` command in each build stage is not necessary if your
# # project.godot is at the repo root

# # Cache imported assets between runs

stages:
    - import-assets
    - test

cache:
  key: import-assets
  paths:
    - .godot/imported/

unitTests:
  stage: test
  script:
    - ls
    - godot --import --path "$PWD" --headless --quit
    - godot -s addons/gut/gut_cmdln.gd --path "$PWD" -gconfig="test/test_config" -gexit --headless --verbose -gjunit_xml_file="results.xml" -gjunit_xml_timestamp=true
  artifacts:
    when: always
    paths:
      - "results.xml"
    reports:
      junit: "results.xml"
    expire_in: 30 days
#   - import-assets
#   - export
#   - deploy

# variables:
#   EXPORT_NAME: test-project

# # Open the editor to import assets in case the cache was empty or outdated
# import-assets:
#   stage: import-assets
#   script:
#     - godot --headless --verbose --editor --quit

# linux:
#   stage: export
#   script:
#     - mkdir -v -p build/linux
#     - cd $EXPORT_NAME
#     - godot --headless --verbose --export-release "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
#   artifacts:
#     name: $EXPORT_NAME-$CI_JOB_NAME
#     paths:
#       - build/linux

# windows:
#   stage: export
#   script:
#     - mkdir -v -p build/windows
#     - cd $EXPORT_NAME
#     - godot --headless --verbose --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
#   artifacts:
#     name: $EXPORT_NAME-$CI_JOB_NAME
#     paths:
#       - build/windows

# mac:
#   stage: export
#   script:
#     - mkdir -v -p build/mac
#     - cd $EXPORT_NAME
#     - godot --headless --verbose --export-release "Mac OSX" ../build/mac/$EXPORT_NAME.zip
#   artifacts:
#     name: $EXPORT_NAME-$CI_JOB_NAME
#     paths:
#       - build/mac

# web:
#   stage: export
#   script:
#     - mkdir -v -p build/web
#     - cd $EXPORT_NAME
#     - godot --headless --verbose --export-release "HTML5" ../build/web/index.html
#   artifacts:
#     name: $EXPORT_NAME-$CI_JOB_NAME
#     paths:
#       - build/web

# # Android Debug Job. It will use the generated debug.keystore.
# android_debug:
#   stage: export
#   script:
#     - mkdir -v -p build/android
#     - cd $EXPORT_NAME
#     - godot --headless --verbose --export-debug "Android Debug" ../build/android/$EXPORT_NAME-debug.apk
#   artifacts:
#     name: $EXPORT_NAME-$CI_JOB_NAME
#     paths:
#       - build/android
